### PR TITLE
Roose commits

### PR DESCRIPTION
**Pull request by benroose**
Dear Paul Kolano,
For the last 6 months I have been using ballast within a virtual cluster on top of OpenStack for Wichita State University's computer science dept. ballast is fantastic program for those of us who love SSH and is exactly what I needed for transparent load-balancing of SSH connections!!

For our systems I wanted to integrate ballast with systemd and apache guacamole. So have added three features:
1. systemd service and socket files for ease of managing ballastd via the systemctl command
2. use_ip_address for ballast-agent to pass the back-end host's IP address rather than its hostname
3. ballastd --jsondump option for outputting host and load data to a machine readable JSON format

I am not an experienced perl programmer, so my additions may be a little rough around the edges. However, I thought it might be of use to you to possibly add some of these extra features into the upstream project. Please feel free to rewrite, adjust, or throw out any of my commits.

Please let me know if you have questions, and thank you for such a useful SSH project for managing load-balanced clusters of machines.

Best regards,
Ben

### CODE REVIEW

**Comment by pkolano** [comment]
hi Ben,

So sorry, just saw this now!  Must not have github email notifications configured correctly.  I will take a look at your changes and get back to you soon.

**Comment by pkolano** [comment]
I integrated your changes with a few minor mods in v2.2.  I don't really know what I'm doing in git, so it wasn't a clean merge from that perspective.  Thanks for the contribution.

**Comment by notpeter** [comment]
Relevant commit for v2.2: https://github.com/pkolano/ballast/commit/9193e899cb0ec450e9a896ad29e28c4421a7eebe

**Comment by benroose** [comment]
Dear Paul,
I fully understand that merging pull requests via git can be complex. Thank you so much for integrating my additions and adding me as a contributor in the [ballast changes file](https://github.com/pkolano/ballast/blob/master/CHANGES).
Best regards,
Ben

**Pull request closed without merging**
