### PR TITLE
Debian packaging files for version 2.2

### PR DESCRIPTION
**Pull request by jonathonf**
This PR adds packaging files/metadata to allow easy packaging for Debian/Ubuntu with "full" systemd support (e.g. timer instead of cron job).

Points of note:
* Only Perl elements packaged
* systemd timer to run agent
* changed `ballastd` installation target to `/usr/sbin`
* install source `ballastrc` as an "example" file only and check for presence of `/etc/ballastrc` for service start
* don't enable services by default on installation; this is a deviation from "normal" Debian practices

### CODE REVIEW

**Comment by pkolano** [comment]
sorry, just saw this.  Will take a look

**Comment by jonathonf** [comment]
No worries. After I submitted this I realised that some parts might be better merged in separately from the packaging files, e.g. the `ballast-agent.timer` isn't Debian-specific.

Just let me know if splitting the PR into smaller parts etc. would be better.

**Comment by pkolano** [comment]
Merged changes.  May tweak as needed with another small change I have for 2.3.  Thanks for your contribution.  Sorry it took so long.

**Comment by pkolano** [comment]
Merged changes.  May tweak as needed with another small change I have for 2.3.  Thanks for your contribution.  Sorry it took so long.

**Pull request merged**
